### ISSUE TITLE
Border style incorrectly applied

### ISSUE THREAD

**Issue by martybarber** [premailer/premailer#152]
If an element has different border colours specified by hex colour codes, the inline style produced is incorrect. Simple example below:

``` css
.example{
  border-top: 1px solid #000;
  border-left: 1px solid #fff;
  border-right:1px solid #fff;
  border-bottom: 1px solid #000;
}
```

Will result in the following inline style 

``` html
<div class="example" style="border: 1px solid #000#fff;">
```

This doesn't seem to occur if using colour names.
