### ISSUE TITLE
group selector contains body tag ignore other selectors

### ISSUE THREAD

**Issue by bastengao** [premailer/premailer#228]
I have a html page ref a s stylesheet, stylesheet content

``` css
body, table, th, td {
  font-family: xxx;
}
```

processed html result, only contains this under body tag

``` html
<body>
<style type="text/css">
body {
  font-family: xxx;
}
</style>
```

it works on development, but on production style of table, th and td elements is empty. 

I expect this

``` html
<body style="font-family: xxx;">
  <table  style="font-family: xxx;">
    <tr>
     <th  style="font-family: xxx;"></th>
     <td  style="font-family: xxx;"></td>
    <tr>
  </table>
</body>
```

I see precompiled style content is 

``` css
@charset "UTF-8";body,table,th,td{family:xxx}...
```

then i test same style content at local, it doesn't work also, but it works when i append space before body.

``` css
@charset "UTF-8"; body,table,th,td{family:xxx}...
```
