### ISSUE TITLE
background-size shorthand getting stripped after inline

### ISSUE THREAD

**Issue by ronnieduke** [premailer/premailer#252]
Given the following CSS:

```css
.header{
background:url('image.jpg') no-repeat 0px 0px / cover;
}
```

The resulting inlined css is 

`<td class="header" style="background:url('image.jpg') no-repeat 0px 0px;>`

removing the `/ cover` shorthand property for background size.

I am needing the shorthand version of this to work because gmail does not support the background-size property, but if you use it via shorthand, it will work with gmail.
