### ISSUE TITLE
CSS Variables

### ISSUE THREAD

**Issue by dorianmariefr** [premailer/premailer#410]
Would be nice to have:

```css
html {
  --opacity: 0.8;
  --color: rgba(50, 100, 25, var(--opacity));
}

p {
  color: var(--color);
}
```

this is how tailwindcss works for instance
